# Generated by Django 4.2.1 on 2023-05-18 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('item', models.CharField(max_length=250, verbose_name='Тип обладнання')),
                ('status', models.CharField(default='У очікуванні завершення', max_length=120)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(max_length=500, verbose_name='Додаток')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees', verbose_name='Працівник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
