# Generated by Django 4.2.1 on 2023-06-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_requestdevice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdevice',
            name='notes',
            field=models.TextField(blank=True, max_length=500, verbose_name='Додаток'),
        ),
    ]
