# Generated by Django 4.2.1 on 2023-05-18 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True, verbose_name='Назва міста')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150, unique=True, verbose_name='Назва відділу')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='null', max_length=100, verbose_name='Локація')),
                ('comments', models.TextField(default='null', max_length=500, verbose_name='Коментарі')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.cities', verbose_name='Назва міста')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default='default_user.jpg', upload_to='photos/', verbose_name='Фото співробітника')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ім`я')),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('eid', models.CharField(max_length=10, unique=True, verbose_name='Внутрішній номер')),
                ('title', models.CharField(max_length=150, verbose_name='Посада')),
                ('mobilephone', models.CharField(max_length=14, unique=True, verbose_name='Мобільний телефон')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.departments', verbose_name='Назва відділу')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.locations', verbose_name='Локація')),
                ('user', models.OneToOneField(limit_choices_to={'is_employee': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
