# Generated by Django 4.1.7 on 2023-05-21 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ustatus",
                    models.CharField(
                        default="",
                        max_length=50,
                        unique=True,
                        verbose_name="Форма роботи",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="departments",
            name="department",
        ),
        migrations.RemoveField(
            model_name="employees",
            name="user",
        ),
        migrations.AddField(
            model_name="departments",
            name="dep_title",
            field=models.CharField(
                default="", max_length=100, unique=True, verbose_name="Назва відділу"
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="comments",
            field=models.TextField(
                blank=True,
                default="",
                max_length=300,
                null=True,
                verbose_name="Коментарі",
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="email",
            field=models.EmailField(
                default="", max_length=75, unique=True, verbose_name="Електрона пошта *"
            ),
        ),
        migrations.AddField(
            model_name="employees",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID Користувача *",
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="city",
            field=models.CharField(
                default="", max_length=100, unique=True, verbose_name="Назва міста"
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.departments",
                verbose_name="Назва відділу *",
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="eid",
            field=models.CharField(
                default="", max_length=8, unique=True, verbose_name="Внутрішній номер *"
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="first_name",
            field=models.CharField(default="", max_length=50, verbose_name="Ім'я *"),
        ),
        migrations.AlterField(
            model_name="employees",
            name="last_name",
            field=models.CharField(
                default="", max_length=50, verbose_name="Прізвище *"
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.cities",
                verbose_name="Назва міста",
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="mobilephone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                null=True,
                verbose_name="Мобільний телефон",
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="photo",
            field=models.FileField(
                blank=True,
                default="default_user.jpg",
                null=True,
                upload_to="photos/",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="title",
            field=models.CharField(
                default="", max_length=50, null=True, verbose_name="Посада *"
            ),
        ),
        migrations.DeleteModel(
            name="Locations",
        ),
        migrations.AddField(
            model_name="employees",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.userstatus",
                verbose_name="Форма роботи",
            ),
        ),
    ]
