# Generated by Django 4.1.7 on 2023-05-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_alter_departments_dep_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departments",
            name="dep_title",
        ),
        migrations.AddField(
            model_name="departments",
            name="department",
            field=models.CharField(
                default="", max_length=100, unique=True, verbose_name="Назва відділу"
            ),
        ),
    ]
