# Generated by Django 4.1.7 on 2023-05-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_alter_cities_city_alter_departments_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="email",
            field=models.EmailField(
                max_length=75, null=True, unique=True, verbose_name="Електрона пошта *"
            ),
        ),
    ]
