# Generated by Django 4.1.7 on 2023-05-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_alter_employees_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="eid",
            field=models.CharField(
                max_length=8, null=True, unique=True, verbose_name="Внутрішній номер *"
            ),
        ),
    ]
