# Generated by Django 4.1.7 on 2023-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0009_alter_employees_eid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="email",
            field=models.EmailField(
                max_length=75, null=True, verbose_name="Електрона пошта *"
            ),
        ),
    ]
