# Generated by Django 4.1.7 on 2023-06-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0011_alter_employees_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="photo",
            field=models.FileField(
                blank=True,
                default="photos/default_user.jpg",
                null=True,
                upload_to="photos/",
                verbose_name="Фото",
            ),
        ),
    ]
