# Generated by Django 4.1.7 on 2023-05-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicewarranty",
            name="comments",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                null=True,
                verbose_name="Коментарі",
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="comments",
            field=models.TextField(
                blank=True,
                default="",
                max_length=500,
                null=True,
                verbose_name="Коментарі",
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="device_model",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Модель обладнання",
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="device_title",
            field=models.CharField(
                default="", max_length=250, verbose_name="Назва обладнання"
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="device_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assets.devicetype",
                verbose_name="Тип обладнання",
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="device_warranty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.devicewarranty",
                verbose_name="Термін гарантії",
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="purchase_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата придбання"
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="serial_number",
            field=models.CharField(
                blank=True,
                default="No Serial",
                max_length=40,
                verbose_name="Серійний номер",
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.suppliers",
                verbose_name="Постачальник",
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.employees",
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="devicestatus",
            name="dev_status",
            field=models.CharField(
                default="",
                max_length=100,
                unique=True,
                verbose_name="Статус обладнання",
            ),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="dev_type",
            field=models.CharField(
                default="", max_length=100, unique=True, verbose_name="Тип обладнання"
            ),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="dev_type_logo",
            field=models.FileField(
                blank=True,
                default="dev_type.jpg",
                null=True,
                upload_to="dev_types/",
                verbose_name="Логотип",
            ),
        ),
        migrations.AlterField(
            model_name="devicewarranty",
            name="warranty",
            field=models.CharField(
                default="", max_length=100, unique=True, verbose_name="Термін гарантії"
            ),
        ),
        migrations.AlterField(
            model_name="suppliers",
            name="comments",
            field=models.TextField(
                blank=True,
                default="",
                max_length=300,
                null=True,
                verbose_name="Коментарі",
            ),
        ),
        migrations.AlterField(
            model_name="suppliers",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Електрона пошта (EMail)",
            ),
        ),
        migrations.AlterField(
            model_name="suppliers",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                null=True,
                verbose_name="Номер телефону",
            ),
        ),
        migrations.AlterField(
            model_name="suppliers",
            name="title",
            field=models.CharField(
                default="",
                max_length=150,
                unique=True,
                verbose_name="Назва постачальника",
            ),
        ),
        migrations.AlterField(
            model_name="suppliers",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                null=True,
                unique=True,
                verbose_name="Сайт постачальника (URL)",
            ),
        ),
        migrations.AlterField(
            model_name="vendors",
            name="url",
            field=models.URLField(
                blank=True, default="", null=True, verbose_name="Сайт виробника (URL)"
            ),
        ),
        migrations.AlterField(
            model_name="vendors",
            name="vendor",
            field=models.CharField(
                default="",
                max_length=100,
                unique=True,
                verbose_name="Виробник обладнання",
            ),
        ),
        migrations.AlterField(
            model_name="vendors",
            name="vendor_logo",
            field=models.FileField(
                blank=True,
                default="dev_vendor.jpg",
                null=True,
                upload_to="vendors/",
                verbose_name="Логотип",
            ),
        ),
    ]
