# Generated by Django 4.2.1 on 2023-05-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.FileField(default='def-logo.jpg', upload_to='company/', verbose_name='Логотип компанії')),
                ('company_title', models.CharField(default='', max_length=200, unique=True, verbose_name='Назва компанії')),
                ('company_code', models.CharField(default='', max_length=8, unique=True, verbose_name='Код ЄДРПОУ')),
                ('address', models.CharField(max_length=250, null=True, verbose_name='Адреса')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Електрона пошта')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Номер телефона')),
                ('comments', models.TextField(default='', max_length=500, null=True, verbose_name='Додаткові коментарі:')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.cities', verbose_name='Місто')),
                ('company_boss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_boss', to='employees.employees', verbose_name='Директор')),
                ('product_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_owner', to='employees.employees', verbose_name='МВ Особа')),
            ],
        ),
    ]
