# Generated by Django 4.1.7 on 2023-05-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                null=True,
                verbose_name="Адреса компанії",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.cities",
                verbose_name="Назва міста",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="comments",
            field=models.TextField(
                blank=True,
                default="",
                max_length=300,
                null=True,
                verbose_name="Коментарі",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_boss",
            field=models.ForeignKey(
                blank=True,
                help_text="Оберіть відповідного співробітника",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_boss",
                to="employees.employees",
                verbose_name="Директор компанії",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_code",
            field=models.CharField(
                default="", max_length=8, unique=True, verbose_name="Код ЄДРПОУ *"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_logo",
            field=models.FileField(
                blank=True,
                default="def-logo.jpg",
                null=True,
                upload_to="company/",
                verbose_name="Логотип компанії",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_title",
            field=models.CharField(
                default="", max_length=200, unique=True, verbose_name="Назва компанії *"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="Електрона пошта",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                null=True,
                verbose_name="Номер телефону",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="product_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Оберіть відповідного співробітника",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_owner",
                to="employees.employees",
                verbose_name="Матеріально-відповідальна особа",
            ),
        ),
    ]
